"""M2 · 电商订单处理：渠道/店铺/渠道商品映射/订单/异常/同步日志

Revision ID: a5077af08db3
Revises: 0001
Create Date: 2026-10-02 17:02:02.582445
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.Enum('taobao', 'douyin', 'shopify', 'jd', 'pdd', 'other', name='channel_platform'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_channels_code')
    )
    op.create_index(op.f('ix_channels_created_at'), 'channels', ['created_at'], unique=False)
    op.create_table('channel_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'code', name='uq_shops_channel_code')
    )
    op.create_index(op.f('ix_channel_shops_created_at'), 'channel_shops', ['created_at'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('import_csv', 'import_json', 'adapter', 'manual', name='order_source'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('created_orders', sa.Integer(), nullable=False),
    sa.Column('duplicate_orders', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('reserved_orders', sa.Integer(), nullable=False),
    sa.Column('exception_orders', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_created_at'), 'import_batches', ['created_at'], unique=False)
    op.create_table('channel_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('channel_product_code', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('channel_title', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['channel_shops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'channel_product_code', name='uq_channel_product_code')
    )
    op.create_index(op.f('ix_channel_products_created_at'), 'channel_products', ['created_at'], unique=False)
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('channel_order_no', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'pending_fulfillment', 'reserved', 'picking', 'shipped', 'completed', 'cancelled', 'exception', name='order_status'), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('buyer_nick', sa.String(length=64), nullable=False),
    sa.Column('total_amount_cents', sa.Integer(), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('import_csv', 'import_json', 'adapter', 'manual', name='order_source'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shop_id'], ['channel_shops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'channel_order_no', name='uq_orders_channel_no'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_sales_orders_created_at'), 'sales_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_sales_orders_order_no'), 'sales_orders', ['order_no'], unique=False)
    op.create_table('order_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('stock_shortage', 'mapping_missing', 'other', name='exception_type'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', 'ignored', name='exception_status'), nullable=False),
    sa.Column('required_qty', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_exceptions_created_at'), 'order_exceptions', ['created_at'], unique=False)
    op.create_table('order_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('channel_order_no', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('created', 'duplicate', 'failed', name='sync_result'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_id'], ['channel_shops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_sync_logs_created_at'), 'order_sync_logs', ['created_at'], unique=False)
    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('channel_product_code', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_items_created_at'), 'sales_order_items', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_order_items_created_at'), table_name='sales_order_items')
    op.drop_table('sales_order_items')
    op.drop_index(op.f('ix_order_sync_logs_created_at'), table_name='order_sync_logs')
    op.drop_table('order_sync_logs')
    op.drop_index(op.f('ix_order_exceptions_created_at'), table_name='order_exceptions')
    op.drop_table('order_exceptions')
    op.drop_index(op.f('ix_sales_orders_order_no'), table_name='sales_orders')
    op.drop_index(op.f('ix_sales_orders_created_at'), table_name='sales_orders')
    op.drop_table('sales_orders')
    op.drop_index(op.f('ix_channel_products_created_at'), table_name='channel_products')
    op.drop_table('channel_products')
    op.drop_index(op.f('ix_import_batches_created_at'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_channel_shops_created_at'), table_name='channel_shops')
    op.drop_table('channel_shops')
    op.drop_index(op.f('ix_channels_created_at'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
