"""M3 · 仓库发货：发货单 / 拣货明细 / 扫码记录 + SKU 默认拣货库位

Revision ID: ea936d1760d0
Revises: 0002
Create Date: 2026-10-02 19:59:00.345512
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0003"
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_no', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'picking', 'picked', 'packed', 'shipped', 'cancelled', name='shipment_status'), nullable=False),
    sa.Column('picker_id', sa.Integer(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('packed_by', sa.Integer(), nullable=True),
    sa.Column('packed_at', sa.DateTime(), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('tracking_no', sa.String(length=64), nullable=False),
    sa.Column('shipped_by', sa.Integer(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picker_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipped_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_no', name='uq_shipments_no')
    )
    op.create_index(op.f('ix_shipments_created_at'), 'shipments', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_no'), 'shipments', ['shipment_no'], unique=False)
    # 一个订单最多只能有一张「未取消」的发货单。部分唯一索引是真正阻止两台
    # 仓库平板同时开同一张拣货单的机制，纯服务层校验会并发漏过。
    op.create_index(
        'uq_shipments_active_order',
        'shipments',
        ['order_id'],
        unique=True,
        sqlite_where=sa.text("status != 'cancelled'"),
        postgresql_where=sa.text("status != 'cancelled'"),
    )
    op.create_table('shipment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('picked_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'picked', name='shipment_item_status'), nullable=False),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('picked_by', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['picked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_items_created_at'), 'shipment_items', ['created_at'], unique=False)
    op.create_table('pick_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('shipment_item_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('ok', 'wrong_sku', 'barcode_not_found', 'over_quantity', 'not_on_list', name='pick_result'), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_item_id'], ['shipment_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pick_records_created_at'), 'pick_records', ['created_at'], unique=False)
    # SQLite 不支持 ALTER TABLE ADD CONSTRAINT，batch 模式会重建表；
    # PostgreSQL 上会退化成普通 ALTER。外键必须显式命名，否则无法回滚。
    with op.batch_alter_table('inventory_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_inventory_stocks_default_location',
            'warehouse_locations',
            ['default_location_id'],
            ['id'],
            ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_stocks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_stocks_default_location', type_='foreignkey')
        batch_op.drop_column('default_location_id')
    op.drop_index(op.f('ix_pick_records_created_at'), table_name='pick_records')
    op.drop_table('pick_records')
    op.drop_index(op.f('ix_shipment_items_created_at'), table_name='shipment_items')
    op.drop_table('shipment_items')
    op.drop_index('uq_shipments_active_order', table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_no'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_at'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
