"""M4 · 采购与收货：供应商 / 采购单 / 收货单 + 库存流水补在途与次品前后值

Revision ID: 0869063ee87f
Revises: 0003
Create Date: 2026-10-02 20:25:26.548105
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0004"
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('contact_name', sa.String(length=64), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('payment_terms', sa.String(length=64), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_suppliers_code')
    )
    op.create_index(op.f('ix_suppliers_created_at'), 'suppliers', ['created_at'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_no', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'partial', 'received', 'cancelled', name='purchase_order_status'), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=True),
    sa.Column('expected_at', sa.DateTime(), nullable=True),
    sa.Column('total_amount_cents', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_no', name='uq_purchase_orders_no')
    )
    op.create_index(op.f('ix_purchase_orders_created_at'), 'purchase_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('defective_qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_items_created_at'), 'purchase_order_items', ['created_at'], unique=False)
    op.create_table('purchase_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('posted', 'cancelled', name='receipt_status'), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no', name='uq_purchase_receipts_no')
    )
    op.create_index(op.f('ix_purchase_receipts_created_at'), 'purchase_receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_purchase_receipts_order_id'), 'purchase_receipts', ['order_id'], unique=False)
    op.create_index(op.f('ix_purchase_receipts_receipt_no'), 'purchase_receipts', ['receipt_no'], unique=False)
    op.create_table('purchase_receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('defective_qty', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['purchase_order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['purchase_receipts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_receipt_items_created_at'), 'purchase_receipt_items', ['created_at'], unique=False)
    # 已有流水行需要默认值，否则 NOT NULL 加不上去
    op.add_column('inventory_transactions', sa.Column('in_transit_before', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('inventory_transactions', sa.Column('in_transit_after', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('inventory_transactions', sa.Column('defective_before', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('inventory_transactions', sa.Column('defective_after', sa.Integer(), nullable=False, server_default='0'))
    # inventory_transactions.type 新增了一个取值 purchase_defective（采购次品入库）。
    # SQLite 把枚举存成 VARCHAR，不需要也不支持改类型；PostgreSQL 用的是原生
    # 枚举类型，必须显式把新取值加进去，否则写入会直接报错。
    if op.get_bind().dialect.name == 'postgresql':
        op.execute(
            "ALTER TYPE inventory_tx_type ADD VALUE IF NOT EXISTS 'purchase_defective'"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 枚举取值无法安全移除（可能已有数据在用），回滚时保留该取值。
    pass
    op.drop_column('inventory_transactions', 'defective_after')
    op.drop_column('inventory_transactions', 'defective_before')
    op.drop_column('inventory_transactions', 'in_transit_after')
    op.drop_column('inventory_transactions', 'in_transit_before')
    op.drop_index(op.f('ix_purchase_receipt_items_created_at'), table_name='purchase_receipt_items')
    op.drop_table('purchase_receipt_items')
    op.drop_index(op.f('ix_purchase_receipts_receipt_no'), table_name='purchase_receipts')
    op.drop_index(op.f('ix_purchase_receipts_order_id'), table_name='purchase_receipts')
    op.drop_index(op.f('ix_purchase_receipts_created_at'), table_name='purchase_receipts')
    op.drop_table('purchase_receipts')
    op.drop_index(op.f('ix_purchase_order_items_created_at'), table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_created_at'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_suppliers_created_at'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
