"""M5 · 多仓库调拨：调拨单 / 调拨明细（在途记在调入仓）

Revision ID: 7a93666bea17
Revises: 0004
Create Date: 2026-10-02 20:26:11.526443
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0005"
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_no', sa.String(length=32), nullable=False),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'in_transit', 'received', 'rejected', 'cancelled', name='transfer_status'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.String(length=255), nullable=False),
    sa.Column('shipped_by', sa.Integer(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('received_by', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipped_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_no', name='uq_stock_transfers_no')
    )
    op.create_index(op.f('ix_stock_transfers_created_at'), 'stock_transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_transfers_transfer_no'), 'stock_transfers', ['transfer_no'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shipped_qty', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Integer(), nullable=False),
    sa.Column('defective_qty', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfer_items_created_at'), 'stock_transfer_items', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_transfer_items_created_at'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfers_transfer_no'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_created_at'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    # ### end Alembic commands ###
