"""M6 · 库存预警：预警规则 / 预警 / 补货建议 + 通知与投递记录

Revision ID: 050f7ab2e28a
Revises: 0005
Create Date: 2026-10-02 21:45:33.595064
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0006"
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('inapp', 'email', 'webhook', name='notification_channel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', name='uq_notification_setting_channel')
    )
    op.create_index(op.f('ix_notification_settings_created_at'), 'notification_settings', ['created_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('info', 'warning', 'error', name='notification_level'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_key', sa.String(length=96), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index('ix_notifications_category', 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_read', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('scope', sa.Enum('global', 'category', 'sku', 'warehouse', name='alert_rule_scope'), nullable=False),
    sa.Column('spu_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('threshold_qty', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_channels', sa.String(length=120), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spu_id'], ['spus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'spu_id', 'sku_id', 'warehouse_id', name='uq_alert_rule_target')
    )
    op.create_index(op.f('ix_alert_rules_created_at'), 'alert_rules', ['created_at'], unique=False)
    op.create_index('ix_alert_rules_enabled', 'alert_rules', ['enabled'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('inapp', 'email', 'webhook', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'retrying', 'failed', 'skipped', name='delivery_status'), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deliveries_pending', 'notification_deliveries', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_created_at'), 'notification_deliveries', ['created_at'], unique=False)
    op.create_table('replenishment_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_no', sa.String(length=32), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('avg_daily_sales', sa.Float(), nullable=False),
    sa.Column('forecast_qty', sa.Integer(), nullable=False),
    sa.Column('safety_qty', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('in_transit_qty', sa.Integer(), nullable=False),
    sa.Column('suggested_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'converted', 'dismissed', name='suggestion_status'), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_key', sa.String(length=96), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key', name='uq_replenishment_dedup'),
    sa.UniqueConstraint('suggestion_no', name='uq_replenishment_no')
    )
    op.create_index(op.f('ix_replenishment_suggestions_created_at'), 'replenishment_suggestions', ['created_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_no', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('low_stock', 'out_of_stock', name='alert_type'), nullable=False),
    sa.Column('status', sa.Enum('open', 'acked', 'resolved', name='alert_status'), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('in_transit_qty', sa.Integer(), nullable=False),
    sa.Column('safety_qty', sa.Integer(), nullable=False),
    sa.Column('gap_qty', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('dedup_key', sa.String(length=96), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_no', name='uq_alerts_no'),
    sa.UniqueConstraint('dedup_key', name='uq_alerts_dedup')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_status_type', 'alerts', ['status', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status_type', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_replenishment_suggestions_created_at'), table_name='replenishment_suggestions')
    op.drop_table('replenishment_suggestions')
    op.drop_index(op.f('ix_notification_deliveries_created_at'), table_name='notification_deliveries')
    op.drop_index('ix_deliveries_pending', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('ix_alert_rules_enabled', table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_created_at'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('ix_notifications_category', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_settings_created_at'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
