"""M7 · 退货与盘点：退货单 / 质检分流 / 盘点单 / 差异调整

Revision ID: 7314144ea4ac
Revises: 0006
Create Date: 2026-10-02 21:46:14.867419
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0007"
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocktakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stocktake_no', sa.String(length=32), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'cancelled', name='stocktake_status'), nullable=False),
    sa.Column('scope', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stocktake_no', name='uq_stocktakes_no')
    )
    op.create_index(op.f('ix_stocktakes_created_at'), 'stocktakes', ['created_at'], unique=False)
    op.create_index(op.f('ix_stocktakes_stocktake_no'), 'stocktakes', ['stocktake_no'], unique=False)
    op.create_table('stocktake_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stocktake_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('book_qty', sa.Integer(), nullable=False),
    sa.Column('counted_qty', sa.Integer(), nullable=True),
    sa.Column('counted_by', sa.Integer(), nullable=True),
    sa.Column('counted_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('adjusted', sa.Boolean(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['counted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stocktake_id'], ['stocktakes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocktake_items_created_at'), 'stocktake_items', ['created_at'], unique=False)
    op.create_table('return_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_no', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('channel_order_no', sa.String(length=64), nullable=False),
    sa.Column('buyer_nick', sa.String(length=64), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'inspected', 'inbound', 'cancelled', name='return_status'), nullable=False),
    sa.Column('reason', sa.Enum('quality', 'wrong_item', 'damaged', 'no_longer_wanted', 'other', name='return_reason'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('inspected_by', sa.Integer(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(), nullable=True),
    sa.Column('inbound_by', sa.Integer(), nullable=True),
    sa.Column('inbound_at', sa.DateTime(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inbound_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_no', name='uq_return_orders_no')
    )
    op.create_index(op.f('ix_return_orders_channel_order_no'), 'return_orders', ['channel_order_no'], unique=False)
    op.create_index(op.f('ix_return_orders_created_at'), 'return_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_return_orders_return_no'), 'return_orders', ['return_no'], unique=False)
    op.create_table('return_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sold_qty', sa.Integer(), nullable=False),
    sa.Column('disposition', sa.Enum('resellable', 'defective', 'repair', 'scrap', name='return_disposition'), nullable=True),
    sa.Column('resellable_qty', sa.Integer(), nullable=False),
    sa.Column('defective_qty', sa.Integer(), nullable=False),
    sa.Column('repair_qty', sa.Integer(), nullable=False),
    sa.Column('scrap_qty', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['return_id'], ['return_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_order_items_created_at'), 'return_order_items', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_return_order_items_created_at'), table_name='return_order_items')
    op.drop_table('return_order_items')
    op.drop_index(op.f('ix_return_orders_return_no'), table_name='return_orders')
    op.drop_index(op.f('ix_return_orders_created_at'), table_name='return_orders')
    op.drop_index(op.f('ix_return_orders_channel_order_no'), table_name='return_orders')
    op.drop_table('return_orders')
    op.drop_index(op.f('ix_stocktake_items_created_at'), table_name='stocktake_items')
    op.drop_table('stocktake_items')
    op.drop_index(op.f('ix_stocktakes_stocktake_no'), table_name='stocktakes')
    op.drop_index(op.f('ix_stocktakes_created_at'), table_name='stocktakes')
    op.drop_table('stocktakes')
    # ### end Alembic commands ###
